on: [push, pull_request]
name: e2e-test
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Tools
        run: ./e2e/get_tools.sh
          
          
      - name: Setup Cluster
        run: ./e2e/setup_cluster.sh
      
      - name: E2E
        run: |
          ./e2e/bin/kind get kubeconfig > /tmp/kubeconfig
          export KUBECONFIG=/tmp/kubeconfig
          go test -v ./e2e/test -e2e
        