name: push-master
on:
  push:
    branches:
      - master
env:
  image-push-owner: 'k8snetworkplumbingwg'
jobs:
  push-master:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      REPOSITORY: ghcr.io/${{ github.repository }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.repository_owner == 'k8snetworkplumbingwg'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        if: github.repository_owner == 'k8snetworkplumbingwg'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:snapshot
          platforms: linux/amd64
          sbom: false
          provenance: false
